### ISSUE TITLE
Want help testing 4k compatibility 

### ISSUE THREAD

**Issue by YeahImRose** [YeahImRose/BetterUIScale#4]
I don't have any access to test my mod with a 4k monitor, so if anyone has used it on 4k or knows someone willing to test it, please let me know if the scaling looks good on 4k.

**Comment by mrGRINCH** [comment]
I'm available to help with 4k compatibility.

**Comment by TheOneAndOnlyDanSan** [comment]
i can test it on 4k

**Comment by YeahImRose** [comment]
I now have a 4k monitor so expect better 4k scaling :)
